### ISSUE TITLE
noargdiff not defined

### ISSUE THREAD

**Issue by hhaensel** [probcomp/Gen.jl#109]
running the example `decode` I received an error that `noargdiff` was not defined.

https://github.com/probcomp/Gen/blob/82cf9f78c93f2e20cbe8884f3c76349b637a4db1/examples/decode/run.jl#L79 and some lines below.

I replaced `noargdiff` by `(NoChange(),)` to get it running. There could be some overlap with #50?

**Comment by marcoct** [comment]
Thanks! This has been fixed in https://github.com/probcomp/Gen/commit/61093889a8d4793a7181d98aab276e6205a5f504..
