### ISSUE TITLE
Docstring of `Gen.metropolis_hastings` should say whether it always returns the proposed trace, or sometimes returns the original trace

### ISSUE THREAD

**Issue by bzinberg** [probcomp/Gen.jl#114]
Until now I thought `Gen.metropolis_hastings` always returns the proposed trace, and the user has to look at `accepted::Bool` to tell how to interpret the result.  However I see now that the tutorial acts as if the original trace is returned when `accepted` is `false`:
https://github.com/probcomp/gen-quickstart/blob/9491b7b879e689242377f710a744d56097e888ee/tutorials/Iterative%20inference%20in%20Gen.ipynb?short_path=0ba3c00#L496

The docstring of `Gen.metropolis_hastings` seems to not specify which is the case.
https://github.com/probcomp/Gen/blob/0062d21152d07b79b5229bc9cdd22f8cc77ab206/src/inference/mh.jl#L20-L27

We should probably say explicitly whether the return value is always equal to the proposed trace or can differ depending on whether the proposal was accepted.

**Comment by marcoct** [comment]
How about adding the following to the end of the first-line description for each of the `mh` methods?

> .., returning the new trace (which is equal to the previous trace if the move was not accepted) and a Bool indicating whether the move was accepted or not.

**Comment by bzinberg** [comment]
SG

**Comment by bzinberg** [comment]
I can do that in a bit

**Comment by marcoct** [comment]
@bzinberg Oh -- I just did it. Thanks for offering though!

Fixed in 90240c647308df648dbe58d6e48c4dcc9d6cf717
