### ISSUE TITLE
Remove mentions of `AddressSet` from the docs

### ISSUE THREAD

**Issue by bzinberg** [probcomp/Gen.jl#131]
I think it corresponds to what is now called `Selection`

**Comment by marcoct** [comment]
@bzinberg I don't see any in the latest version of the documentation at https://probcomp.github.io/Gen/dev/. Note that the version of the docs at https://probcomp.github.io/Gen/stable/ is pretty out of date, because it refers to the last 'released' version which was from March.

**Comment by marcoct** [comment]
Closing this because I don't see any remaining mentions. I fixed some lingering variable name issues in https://github.com/probcomp/Gen/pull/140

**Comment by bzinberg** [comment]
Ah yeah, meant to search through head on my own but didn't get around to it.  Thanks for verifying!
