### ISSUE TITLE
Document distributions DSL

### ISSUE THREAD

**Issue by marcoct** [probcomp/Gen.jl#154]
The "distribution DSL feature" (https://github.com/probcomp/Gen/pull/103) was merged, but isn't yet added to the Gen documentation.

The PR contains a pretty detailed Markdown writeup about the feature.

We might only want to document those parts of the feature that are more stable / tested / complete, or we could explain the missing functionality that might be expected (gradients for vector-valued random choices is one).

**Comment by bzinberg** [comment]
FYI, I am using this now and was lucky I remembered there was an excellent write-up in the PR description.  We should transfer this excellence to the docs soon.

Also, it is working!

**Comment by marcoct** [comment]
Yes, I'm using this feature too in the scene graph inference effort (to produce a labeled categorical). Very useful @alex-lew !

**Comment by ztangent** [comment]
Any chance this will be added to the docs soon? I think it might be especially useful as the class moves forward! (And I've gotten feedback that Gen lacking the ability to easily create your own distributions was somewhat frustrating -- turns out that they (and I) just didn't know about this DSL.)
