### ISSUE TITLE
Error using @ad and @addr

### ISSUE THREAD

**Issue by logankilpatrick** [probcomp/Gen.jl#161]
See https://stackoverflow.com/questions/58856671/what-are-ad-and-addr-macros-in-julia

Is this a known issue? If so, those examples should be removed.

**Comment by alex-lew** [comment]
Hi! It looks like that link points to a commit from over a year ago, when those macros did exist. They’ve since been removed, and I believe the relevant examples have been updated. Closing the issue, but feel free to reopen if you find places we still need to update.

**Comment by logankilpatrick** [comment]
Thank you!  

Best, 
Logan Kilpatrick
