### ISSUE TITLE
Rename repo to Gen.jl

### ISSUE THREAD

**Issue by domluna** [probcomp/Gen.jl#162]
I guess this would be a follow up to https://github.com/probcomp/Gen/commit/7c1c604d495d7db0934a88f8e05352ec7c8b332a

Then when typing gen.jl into a search engine it should take you to this repo!

**Comment by bzinberg** [comment]
Would renaming the repo break existing external links to the issue tracker?  (Hopefully there are smart auto-redirects)

**Comment by domluna** [comment]
afaik github redirects to the new url

that being said you would probably want to update external links

https://help.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by bzinberg** [comment]
Thanks for the pointer.  Yeah, the issue from my end is that I use github permalinks in commit messages to reference GH issues, and I'm not sure it's feasible to modify these past commit descriptions.  The answer might just be to trust the redirects, or failing that, to let the links go stale.

**Comment by ChrisRackauckas** [comment]
Github auto-redirects. This would need to be done to register it to the General registry BTW

**Comment by ViralBShah** [comment]
This keeps coming up on Julia slack. People would love to try out Gen but can't install it in the usual way. If registered in General registry, all the ecosystem tools like juliahub.com, juliaobserver.com etc. can start tracking it, and new Julia releases will then even run it as part of a PkgEval run.

We rename github repos all the time and even move them around to new orgs. Github does all the redirection transparently. Also, it should be easy enough to fix the CI etc.

**Comment by marcoct** [comment]
I just renamed the repo, and submitted the registration PR via Registrator (but only after renaming the repo). Also, the registration did not automatically approve, so there may some followup work, which will be tracked in this issue: https://github.com/probcomp/Gen.jl/issues/260
