### ISSUE TITLE
Literal assignment and selection constructors

### ISSUE THREAD

**Issue by marcoct** [probcomp/Gen.jl#20]
Each argument is a pair of address and value.
The last element of each list is the value.
```
assignment = Assignment(
    :foo => :bar => 0.000123,
    :baz => :blah => -0.3,
    :something => 0.1341
)
```

Each argument is an address:
```
selection = Selection(
   :foo => :bar,
   :baz
)
```

**Comment by marcoct** [comment]
Syntactic sugar for constructing a `DynamicAddressSet` was introduced in https://github.com/probcomp/Gen/commit/b04e4cb4f48cfdea1fc38f55aeeea767bd271dfc

```julia
selection::DynamicAddressSet = select(:foo, :bar, :baz => 1 => :x)
```

**Comment by fsaad** [comment]
How about static?

**Comment by marcoct** [comment]
Users can convert a `DynamicAddressSet` whose top-level keys are all symbols into a `StaticAddressSet` that has type parameters that include the set of top-level keys (to enable code-specialization during JIT-compilation), using:
```
static_addr_set = StaticAddressSet(selection)
```

**Comment by marcoct** [comment]
A literal constructor for a `DynamicAssignment` was added in https://github.com/probcomp/Gen/pull/44:

```
assmt = DynamicAssignment((:x, 1.2), (:y => :z, -2.4)) 
```
