### ISSUE TITLE
Proposal: Make getindex for choicemaps return submaps, not just values

### ISSUE THREAD

**Issue by ztangent** [probcomp/Gen.jl#226]
For a choicemap `choices` with nested addresses, calling `choices[addr]` where `addr` is the address for some sub-choicemap throws a KeyError. One instead needs to do `get_submap(choices, addr)` to access the submap. This is somewhat confusing behavior, and leads to the impression that the submap doesn't exist. It's also non-analogous with the `getindex` behavior for a trace `tr`, where `tr[addr]` gives the return value of the corresponding subtrace. Perhaps it would make sense to change `getindex` for choicemaps so that they return any value OR submap at the requested `addr`, and only throw a keyerror otherwise? Is there any reason things aren't currently implemented this way?

Related to #124, and also suggested in a comment in #89.

**Comment by bzinberg** [comment]
Is this the same as https://github.com/probcomp/Gen/issues/156?

**Comment by ztangent** [comment]
@bzinberg Yes, didn't realize it was already raised there! Happy to close this if that makes sense.

**Comment by bzinberg** [comment]
Let's close this as a dup.  Any input you have on #156 would be appreciated!
