### ISSUE TITLE
Move pretty-printing of choicemaps from `print(::IO, ::ChoiceMap)` to `show(::IO, ::MIME"text/plain", ::ChoiceMap)`

### ISSUE THREAD

**Issue by bzinberg** [probcomp/Gen.jl#227]
When looking up how to get a pretty-printed string for a matrix like it shows up in the REPL [1], I learned piecemeal from [here](https://docs.julialang.org/en/v1/base/strings/#Base.repr-Tuple{Any}), [here](https://docs.julialang.org/en/v1/base/io-network/#Base.Multimedia.display) and [here](https://discourse.julialang.org/t/how-to-print-arrays-inside-functions/4091/4) that `Base.show(::IO, value)` (usually the same piece of logic that governs `print(value)`) is generally supposed to be a condensed one-line string, whereas `Base.show(::IO, ::MIME"text/plain", value)` is the pretty-printed version.  The latter is what shows up in the Julia REPL and Jupyter notebooks when displaying a value.

I think the only place we rely on `Base.show(::IO, ::ChoiceMap)` being a pretty-print is in the tutorial notebooks where we call `print(choicemap)`.  But in those cases I think it's better practice to instead call `display(choicemap)`, which will show the pretty-print version.

Also, after this change is made, evaluating a `ChoiceMap` in the REPL will result in a pretty-print (and an explicit `print(::ChoiceMap)` will not -- instead one can use `display(::ChoiceMap)`), which is nice; see https://github.com/probcomp/Gen/pull/228#issue-397323599.

[1] Answer: `sprint(show, "text/plain", my_matrix)`.

**Comment by marcoct** [comment]
@bzinberg Great!

**Comment by bzinberg** [comment]
Done
