### ISSUE TITLE
"Did not visit all constraints" error in update step & custom proposal

### ISSUE THREAD

**Issue by collinskatie** [probcomp/Gen.jl#242]
Hi, I am trying to have a custom random walk proposal that will perturb the x,y, and rotation of each block in a list of blocks that have been sampled by the generative function. These block properties are then fed into a physics engine, resulting in a set of observations that we are conditioning on (fed through a choicemap). The number of blocks in this list could be any integer >= 0, and the proposal function seeks to update them one at a time. 

However, when I run mh(trace, random_walk_proposal, (block_idx, )), the code fails on the internal update step in Gen. I get the error (this one in particular is a case where there is a single block in :blocks): 

```
ERROR: LoadError: Did not visit all constraints
Stacktrace:
 [1] update(::Gen.DynamicDSLTrace{DynamicDSLFunction{Any}}, ::Tuple{Array{Int64,1}}, ::Tuple{UnknownChange}, ::DynamicChoiceMap) at /Users/kcollins/.julia/packages/Gen/cgJrj/src/dynamic/update.jl:203
```

I've tried printing out the visited and constraints, and get the following:

```
visited
DynamicSelection(Dict{Any,Selection}())
constraints
│
└── 1
    │
    ├── :rot : 19.767793135465038
    │
    ├── :y : 226.0321373161281
    │
    └── :x : 233.5481473731453
```

I've gone through some of Gen's examples, and don't typically get the "empty" Dynamic Selection visited variable, so I'm a bit confused why that may be - and whether it's an issue with the custom proposal? I read in the documentation that "If the proposal modifies addresses that determine control flow in the model, values must be provided by the proposal for any addresses that are newly sampled by the model" -- but we aren't changing the number of blocks in this, it would only change the properties which would change the results of the forward physics simulation, so I don't think that would be the issue? 

Here is the current proposal function: 

```
@gen function random_walk_proposal(trace,block_idx)
    # do a random walk round x,y,rot for block
    # block idx = index into :blocks array in trace 
    {:blocks=>block_idx=>:x} ~ normal(trace[:blocks=>block_idx=>:x], pos_stdev)
    {:blocks=>block_idx=>:y} ~ normal(trace[:blocks=>block_idx=>:y], pos_stdev)
    {:blocks=>block_idx=>:rot} ~ normal(trace[:blocks=>block_idx=>:rot], rot_stdev)
end
```

Thanks for any help on this!

**Comment by marcoct** [comment]
@collinskatie Can you share the model code and the inference loop that calls mh? This might be because the number of blocks is actually zero unexpectedly some how.

**Comment by collinskatie** [comment]
Hi @marcoct - thanks!! The issue was related to the number of blocks and the way I had been using nested addresses in the block traces. All fixed now - thank you so much for your help!
