### ISSUE TITLE
Perhaps `generate` should complain if some of the choices in `constraints` cannot appear in the output trace

### ISSUE THREAD

**Issue by bzinberg** [probcomp/Gen.jl#248]
Example:
```
julia> @gen function f()
         x ~ normal(0, 1)
       end;

julia> constraints = choicemap((:z, 10))
│
└── :z : 10


julia> trace, _ = generate(f, (), constraints);

julia> get_choices(trace)
│
└── :x : 0.05197921899899009

```

As a user, I would expect a warning that `:z` cannot possibly appear in the output trace.

The docs are ambiguous on whether the user is allowed to have something like `:z` in their constraints:

> Return a trace of a generative function that is consistent with the given constraints on the random choices.

I read that as saying "if an address appears in the constraints, then it has to appear in the trace and have this value," but it would also be reasonable to read it as "if an address appears both the trace and the constraints, then the values must agree."

Also, I would definitely expect a warning if the constraints say there should be a choice at a particular address but the trace has a submap there, or vice versa.  And indeed we do get an error: e.g., with `f` defined as above,
```
julia> @gen function g()
         f_result ~ f()
       end;

julia> constraints = Gen.choicemap((:f_result, :some_value))
│
└── :f_result : some_value


julia> trace, _ = generate(g, (), constraints);
ERROR: KeyError: key :f_result not found
Stacktrace:
 [1] get_submap(::DynamicChoiceMap, ::Symbol) at /home/bzinberg/.julia/packages/Gen/R0MfW/src/choice_map.jl:684
 [2] traceat(::Gen.GFGenerateState, ::DynamicDSLFunction{Any}, ::Tuple{}, ::Symbol) at /home/bzinberg/.julia/packages/Gen/R0MfW/src/dynamic/generate.jl:55
```

I'm inclined to say I think there should be an (informative) error in both of the examples above, to help the user catch bugs (including typos) in their inference code.

**Comment by ztangent** [comment]
I think this might be a duplicate of #208 !

**Comment by bzinberg** [comment]
Oh, so that's what "visit" means :slightly_smiling_face:

**Comment by bzinberg** [comment]
Copied my initial comment to https://github.com/probcomp/Gen/issues/208#issuecomment-621974781, thanks.
