### ISSUE TITLE
`@dist` is confused by minus, I think

### ISSUE THREAD

**Issue by bzinberg** [probcomp/Gen.jl#253]
No problem:
```
julia> Gen.@dist f(a, b) = 1 + Gen.uniform(a, b);

julia> f(1, 2)
2.004503805783018
```

But:
```
julia> Gen.@dist f(a, b) = 1 - Gen.uniform(a, b);

julia> f(1, 2)
ERROR: MethodError: no method matching random(::Gen.UniformContinuous, ::Int64)
```

**Comment by alex-lew** [comment]
Opened a quick PR to fix this -- thanks for catching! I think we should be able to merge soon, but @bzinberg if you need something quick, you can also write `@dist f(a, b) = 1 + (-1 * Gen.uniform(a, b))`.

**Comment by bzinberg** [comment]
Thanks for the quick turnaround!  And thanks for the stop-gap, very helpful.
