### ISSUE TITLE
Register Gen.jl in the General registry

### ISSUE THREAD

**Issue by marcoct** [probcomp/Gen.jl#260]
Some relevant comments here: https://github.com/probcomp/Gen.jl/issues/162

Instructions here: https://github.com/JuliaRegistries/General

I used the web app to do this (but before renaming the repo from Gen to Gen.jl). There is a PR in the General registry: https://github.com/JuliaRegistries/General/pull/14808. Some additional work may be required.

**Comment by ChrisRackauckas** [comment]
I think not having a 5 letter name is fine. I would be willing to approve and merge it. But handling the compat stuff will be necessary.

**Comment by ViralBShah** [comment]
I am happy to support the name too.

**Comment by marcoct** [comment]
@ChrisRackauckas Thank you! The compat stuff has been fixed in this PR by registrator: https://github.com/JuliaRegistries/General/pull/15310
