### ISSUE TITLE
After renaming to Gen.jl, link from gen.dev to docs is broken

### ISSUE THREAD

**Issue by Schaechtle** [probcomp/Gen.jl#261]
Clicking on docs here:
![image](https://user-images.githubusercontent.com/9608300/82099762-2409a100-96d6-11ea-9f9a-61f9b231317e.png)
results in a 404 error. This can be fixed by fixing the underlying link from https://probcomp.github.io/Gen/dev/ to https://probcomp.github.io/Gen.jl/dev/

**Comment by cameronfreer** [comment]
Or do we want to change the link to be to the page to which the latter redirects, https://www.gen.dev/dev/ ?

**Comment by cameronfreer** [comment]
Also https://probcomp.github.io/ itself results in a 404 error.
