### ISSUE TITLE
Involution call switches to DynamicChoiceMap from custom GFI ChoiceMap

### ISSUE THREAD

**Issue by femtomc** [probcomp/Gen.jl#307]
When using the involution DSL to define an involutive MH step, the call to `involution` changes the choice map to the `DynamicChoiceMap` type.

E.g. if you sprinkle a few type checks inside the involutive MH call:
```julia
    (fwd_choices, fwd_score, fwd_ret) = propose(proposal, (trace, proposal_args...,))
    println(typeof(fwd_choices))
    (new_trace, bwd_choices, weight) = involution(trace, fwd_choices, fwd_ret, proposal_args)
    println(typeof(bwd_choices))
    (bwd_score, bwd_ret) = assess(proposal, (new_trace, proposal_args...), bwd_choices)
```
this produces:
```julia
Main.InvolutionJaynes.Jaynes.JChoiceMap{Main.InvolutionJaynes.Jaynes.DynamicMap{Main.InvolutionJaynes.Jaynes.Value}}
Gen.DynamicChoiceMap
```
Here `propose` correctly uses my implementation (and thus, my `ChoiceMap`) - now `involution` switches this over to a `DynamicChoiceMap`.

I don't know much about the internals of the involution DSL - but this slightly breaks the interface, because it requires that implementors of the GFI also write `convert(::Type{TheirChoiceMap}, ::DynamicChoiceMap)` in some form (or an explicit conversion in a dispatch to `assess`.

**Comment by alex-lew** [comment]
Does it break the interface? ChoiceMap is an abstract type, so `assess`, `propose`, etc. must all be written to support arbitrary choicemaps as input.

**Comment by femtomc** [comment]
Ah I understand now! Thank you for saving me a good deal of pain later.

**Comment by femtomc** [comment]
Closing due to insight from Alex.
