### ISSUE TITLE
Particle filter test failing on master

### ISSUE THREAD

**Issue by femtomc** [probcomp/Gen.jl#338]
Seems to be a tolerance issue mostly.

```julia
default proposal: Test Failed at /home/mccoy/code/julia/Gen.jl/test/inference/particle_filter.jl:167
  Expression: isapprox(expected_log_ml, actual_log_ml_est, atol = 0.01)
   Evaluated: isapprox(-4.87645083351704, -4.858673528936813; atol = 0.01)
Stacktrace:
 [1] top-level scope at /home/mccoy/code/julia/Gen.jl/test/inference/particle_filter.jl:167
 [2] top-level scope at /home/mccoy/julia/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115
 [3] top-level scope at /home/mccoy/code/julia/Gen.jl/test/inference/particle_filter.jl:147
 [4] top-level scope at /home/mccoy/julia/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115
 [5] top-level scope at /home/mccoy/code/julia/Gen.jl/test/inference/particle_filter.jl:52
Test Summary:      | Pass  Fail  Total
particle filtering |    1     1      2
  custom proposal  |    1            1
  default proposal |          1      1
```

**Comment by marcoct** [comment]
Looks like it passes with Julia 1.4 but fails on Julia 1.5. This might take some work to track down.

**Comment by georgematheos** [comment]
Just wanted to note that I ran into this issue as well.  @marcoct do you have a sense whether it is possible that this is just floating point error, and the solution is just to increase the tolerance?  I am not familiar with the example so don't know whether this type of large error is within the realm of possibility.

It looks like in 1.5, the sequence of numbers produced by the RNG changed (https://docs.julialang.org/en/v1/NEWS/#Random), so it is possible that this type of error was possible before, and the RNG just didn't happen to sample an execution which caused it.

**Comment by prateekrastogi** [comment]
Would be open to share pull requests, if my comment were not to deleted due to racial discrimination.

**Comment by marcoct** [comment]
Fixed in: https://github.com/probcomp/Gen.jl/commit/a14ecc0715ecf4f7f0f70b547cdbdece8c704d02
