### ISSUE TITLE
Method to extract all choice addresses from a choicemap?

### ISSUE THREAD

**Issue by alex-lew** [probcomp/Gen.jl#394]
Currently, the user needs to write their own boilerplate to traverse a choicemap and extract all leaves. It may be worthwhile to provide a built in function for this, like `Gen.get_values_shallow`, but not shallow. 

This could be useful for easier programmatic inspection of choices within a trace, as well as for algorithms like single-site MH which need to randomly choose an address to update. It was also asked about by a user on the Gen Slack recently:

> Excellent! Say I have a trace, I can access an address in the trace with brackets, like trace[:mu] . Is there a convenient way of finding all addresses in a given trace. I was expecting something like keys(trace) , or something similar?

This also raises the question of whether we should implement `keys` on traces / choicemaps, and if so, what the semantics should be: all values you can pass to `getindex`? Only choice addresses?

**Comment by bzinberg** [comment]
Dup of https://github.com/probcomp/Gen.jl/issues/123?

**Comment by alex-lew** [comment]
Yep, thanks!
