### ISSUE TITLE
Use of `isnothing` requires Julia 1.1 and above

### ISSUE THREAD

**Issue by ztangent** [probcomp/Gen.jl#398]
`isnothing` is used several times in the Gen codebase, [which requires Julia 1.1 and above](https://docs.julialang.org/en/v1/base/base/#Base.isnothing). We should either adjust the compatibility in `Project.toml` to require Julia 1.1 or above, or replace calls to `isnothing` with `=== nothing`.

**Comment by bzinberg** [comment]
Are there any reasons we would want compatibility with Julia <1.1?

**Comment by ztangent** [comment]
Julia 1.0 is still the current long-term-support release.

**Comment by ztangent** [comment]
Looks like we need to bump our compatibility to at least Julia 1.3, because that's the first release of Julia which adds methods to abstract types which are callable (which I did for the TraceTranslator type in #397, not sure where else it appears).

**Comment by alex-lew** [comment]
Julia 1.6 is now LTS, so I'm going to close this issue :)
