### ISSUE TITLE
a typo in stable's doc

### ISSUE THREAD

**Issue by cjen07** [probcomp/Gen.jl#40]
in https://probcomp.github.io/Gen/stable/#Generative-Functions,-Traces,-and-Assignments-1
in first code block, line 6
`ys[i] = normal(slope * xs + intercept, 1.)` should be
`ys[i] = normal(slope * x + intercept, 1.)`

**Comment by marcoct** [comment]
We have rewritten the documentation since this was opened and this error does not appear any more.
