### ISSUE TITLE
Posterior inference wrt. return value

### ISSUE THREAD

**Issue by JGameCreation** [probcomp/Gen.jl#402]
Hi! I'm quite new to Gen. The tutorials show how to do posterior inference with some of the random choices constrained to specific values. However, how do you infer the posterior wrt. a specified return value of the generative function? I've tried:
```
observations = Gen.choicemap()
observations[] = false;
```
However, it doesn't work.

**Comment by JGameCreation** [comment]
Basically, the problem is that I want to have constrains on values that are deterministically computed from the random values and then infer the posterior.

**Comment by marcoct** [comment]
@JGameCreation It's not possible in Gen to constrain the return value and do posterior inference conditioned on the return value of a generative function. But you might be interested in this related issue: https://github.com/probcomp/Gen.jl/issues/134, which gives some more context.
