### ISSUE TITLE
`Gen.Trie` does not implement `get_values_shallow`, despite being a `ChoiceMap`

### ISSUE THREAD

**Issue by alex-lew** [probcomp/Gen.jl#444]
The `Gen.Trie` data structure is declared as an instance of the `ChoiceMap` abstract data type (https://github.com/probcomp/Gen.jl/blob/44f5f1408caf05ff95932bb58d9f57907c5084e3/src/trie.jl#L5).

However, there is no implementation of `Gen.get_values_shallow` for it.

One place this comes up is when executing code that returns a trace in an environment like Atom, VS Code, or Pluto.jl. These IDEs allow users to click into compound data and see pretty-printed representations of each component. Because Tries are ChoiceMaps, printing `trace.trie` triggers a call to our ChoiceMap pretty printer (https://github.com/probcomp/Gen.jl/blob/master/src/choice_map.jl#L122), which in turn attempts to call `get_values_shallow` (yielding a Method Not Implemented error).

We could fix either by implementing Gen.get_values_shallow for Tries, or by removing the declaration that a Trie is a ChoiceMap (I have not investigated / thought about the consequences of that option, and am not sure off the top of my head whether a Trie being a ChoiceMap is important elsewhere in the codebase).

**Comment by femtomc** [comment]
I think semantically it makes sense to remove this declaration -- `Trie` forms the basis for `DynamicChoiceMap` instances, but is not the `ChoiceMap` implementor for a modeling language itself.

Furthermore, removing this declaration does not make any of the existing tests fail.

**Comment by femtomc** [comment]
@alex-lew / @ztangent what do you think about this (?)

Ping: @chentau just opened up a PR.

**Comment by ztangent** [comment]
I think if `Trie` is not used as a choice map, then we should remove the declaration!

I'll note that Marco also seems to have left this comment in the source at some point:

https://github.com/probcomp/Gen.jl/blob/44f5f1408caf05ff95932bb58d9f57907c5084e3/src/Gen.jl#L46-L47

**Comment by alex-lew** [comment]
Thanks @chentau for the PR!

The one question I have is whether any part of the code currently depends on using methods on Tries that are defined only for ChoiceMaps. I'm worried that something might have escaped our test suite. But it's probably OK to remove and trust our tests.

**Comment by femtomc** [comment]
@alex-lew if this is the case, I think it’s okay to implement these methods separately from defining a Trie as implementing the choice map interfaces.

Re — I actually remember being confused by this when I first started looking at the Gen internals! I suspect it might be a good idea to remove the declaration from a conceptual point of view (e.g. the standard choice map question: what GenerativeFunction implementor has a Trie choice map?)
