### ISSUE TITLE
Migrate tests from Travis CI to Github Actions

### ISSUE THREAD

**Issue by fsaad** [probcomp/Gen.jl#483]
https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-travis-ci-to-github-actions

As of now we use Github Actions for CompatHelper.yml under `.github/workflows` and Travis for testing and documentation under `.travis.yml`. We should unify all the status checks under Github Actions; some example config files can be found here:
- https://github.com/JuliaPy/PyPlot.jl/blob/master/.github/workflows/
- https://github.com/SciML/DiffEqDocs.jl/tree/master/.github/workflows

Eliminating Travis will also make it easier to incrementally add more checks, such as Formatting and the like, within the Github interface.

**Comment by ztangent** [comment]
Resolved by #484!
