### ISSUE TITLE
Dynamic DSL should use the logpdf_grad method for distributions

### ISSUE THREAD

**Issue by marcoct** [probcomp/Gen.jl#56]
Currently, the dynamic DSL obtains gradients of the log density of a probability distribution by tracking the parameters on the ReverseDiff AD tape and passing them to the `logpdf` method of the distribution, and relying on the `logpdf` method to implemented in a way that plays nicely with ReverseDiff.

The static DSL uses the distributions's `logpdf_grad` method.

The dynamic DSL should also use the distribution's `logpdf_grad` method, for separation of concerns reasons, and for performance.

**Comment by fsaad** [comment]
Ideally the gradient from reverse diff can be used as a test for ensuring
logpdf_grad is implemented correctly.

**Comment by marcoct** [comment]
All the `logpdf_grad` methods are already tested with finite differencing, which I prefer to using ReverseDiff because (1) it does not introduce an extra dependency of the testing code on ReverseDiff, and (2) testing with ReverseDiff would require writing a version of the logpdf method that plays nicely with ReverseDiff, which is unecessary code duplication.
