### ISSUE TITLE
Untraced call to a gen function should sample from the generative distribution, and not use generate

### ISSUE THREAD

**Issue by marcoct** [probcomp/Gen.jl#63]
An untraced call to a gen function should sample from its generative distribution ``p`` (e.g. which is sampled from by `propose`), and not ``q`` (which is sampled from by `generate`). Although in the most typical case this ``q`` is identical to the ``p`` when there are no constraints on `generate`, it is not always.

**Comment by alex-lew** [comment]
Nice -- I was wondering about this. @vkmvkmvkmvkm, this is related to the question of whether a Metaprob `inf`, when called from Clojure, should invoke the implementation and throw away the score (as it does currently), or just invoke the model.

**Comment by marcoct** [comment]
Fixed in 0a327cf776ee6e7008fe8603aa61a1c126dee459
