### ISSUE TITLE
Getting array of independent random samples?

### ISSUE THREAD

**Issue by outlace** [probcomp/Gen.jl#86]
I apologize if this is covered somewhere but it seems like in the tutorials in order to generate an array of random samples you have to use a for loop to populate an array. In Python I can get an arbitary-shaped array of independent random samples by doing something like `numpy.random.rand(4,10,2)` and it will give me an order-3 array of size 4x10x2 with independent uniform samples. Any way to do the same with Gen?

**Comment by marcoct** [comment]
Certain distributions may generate random choices that are arrays. Currently the only built-in distribution that generates array-valued random choices is [mvnormal](https://probcomp.github.io/Gen/dev/ref/distributions/#Gen.mvnormal). Vectorized versions of many built-in distributions for which currently only scalar distributions are available (e.g. `uniform_continuous`) could be added in the future to Gen, but we have not done that yet.
