### ISSUE TITLE
Suggestions for cleaner @trace syntax

### ISSUE THREAD

**Issue by fsaad** [probcomp/Gen.jl#93]
The current implementation of `@trace` already supports spaces instead of parens and commas, i.e.,
```julia
noise = @trace gamma(1,1) :noise
```
although this pattern is not used in the repo.

It would be good to adopt this simpler notation, and switch the location of the address and expression:
```julia
noise = @trace :noise gamma(1,1)
```

Other things that could be helpful include attaching the address to the macro (the following almost works, but the notation below is used in Julia for mapping a macro over a list, apparently)
```julia
noise = @trace[:noise] gamma(1,1)
```

or maybe even using a default address when the lvalue is a simple identifier
```julia
noise = @trace gamma(1,1) # automatically uses :noise
ys[i] = @trace normal(0,1) # either fails, or maybe even desugars to (:y => i)
w = (@trace bernoulli(0.4)) ? 1 : 0 # trickier case
```

**Comment by marcoct** [comment]
@vkmvkmvkmvkm @alex-lew Any opinion on this?

I think that putting the address immediately following `@trace` , and not requiring use of extra parantheses, when not needed, are improvements.

But, maybe this should wait until any other syntax changes that are informed by the distribution combinators work with @alex-lew.

**Comment by alex-lew** [comment]
I agree with moving the address to the beginning! 

I'm not sure about the spaces-not-parentheses. If someone writes

```julia
n = @trace :n geometric(0.5) + 1
```

I'm not sure if it will be obvious that the `+ 1` is not included in the trace. I like that we can catch the error if someone uses parentheses to make explicit what they are trying to trace. But I could go either way.

**Comment by marcoct** [comment]
This has been obviated by recently improved syntax in https://github.com/probcomp/Gen/pull/191:
```julia
noise = ({:noise} ~ gamma(1,1))
```
or with syntactic sugar:
```julia
noise ~ gamma(1, 1)
```
