### ISSUE TITLE
Simplify and document workflow for editing probcomp.github.io/Gen

### ISSUE THREAD

**Issue by fsaad** [probcomp/Gen.jl#94]
Github decides to build a probcomp.github.io/Gen page based on the configuration line:

    https://github.com/probcomp/Gen/settings > Github Pages > Source > "gh pages branch".

According to the documentation: https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages
> You can configure GitHub Pages to publish your site's source files from master, gh-pages, or a /docs folder on your master branch for Project Pages and other Pages sites that meet certain criteria.

Part of the confusion in Gen's repo is that there _is_ a /docs folder on master branch, which Github does _not_ know about (since our Github Pages settings uses the "gh pages" branch). 

Instead the /docs folder is used by [Documenter.jl, which itself uses a combination of Github and Travis](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/), so that on every commit to master, it reads the markdown files in`/docs` and pushes a bunch of HTML files to "gh-pages" branche, which are then hosted by Github at probcomp.github.io/Gen/dev.

To reduce the confusion with /docs on master (which is a Github concept that we do not use), we should rename the folder to `/documentation` and ask Documenter.jl to build from that folder.

In order to manually edit probcomp.github.io, you need to checkout the [gh-pages branch](https://github.com/probcomp/Gen/tree/gh-pages) and edit the markdown files there. **Edits should not be made to files that Documenter.jl writes, such as v.*/, latest/, stable/ version.js**

**Comment by marcoct** [comment]
Documentation added to https://github.com/probcomp/Gen/blob/master/WEBSITE.md
